// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmiskzcagqaeniuxsvlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtaXNremNhZ3FhZW5pdXhzdmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTA4NTQsImV4cCI6MjA3NDU2Njg1NH0.pyBWVq-xQciq1UZPlBqL8O1j1S4xJyvQCABEHQPA1m8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});